export type AchievementBadgeMeta = {
  symbol: string;
  variant: string;
  description: string;
  featured?: boolean;
};

export const ACHIEVEMENT_TITLE_BY_ID: Record<string, string> = {
  apg: "AST - Assists per game",
  "all-defense": "All-DEF",
  "all-nba": "All-NBA",
  "all-rookie-1st": "All-Rookie 1st",
  "all-rookie-2nd": "All-Rookie 2nd",
  "all-star": "AS",
  "all-star-mvp": "AS MVP",
  "aba-all-defense": "ABA All-Defense",
  "aba-all-league": "All-ABA",
  "aba-all-star": "ABA All-Star",
  "aba-all-star-mvp": "ABA AS MVP",
  "aba-assists": "ABA Assist Champ",
  "aba-champ": "ABA Champ",
  "aba-mvp": "ABA MVP",
  "aba-playoffs-mvp": "ABA Playoff MVP",
  "aba-rebounds": "ABA Rebound Champ",
  "aba-roy": "ABA ROY",
  "aba-scoring": "ABA Scoring Champ",
  assists: "AST Champ",
  asts: "Assists",
  "avg-mpg": "Average minutes per game",
  "avg-ts-pct": "Avg true shooting",
  "avg-ts-star": "Average TS+ & TS% combined",
  "avg-ws-48": "Average win shares per 48",
  bpg: "Blocks per game",
  blocks: "BLK Champ",
  championship_rings: "Championships",
  dpoy: "DPOY",
  "sixth-man": "6MOY",
  fmvp: "FMVP",
  "games-started": "GS - Games started",
  goat: "GOAT rank",
  mpg: "Minutes per game",
  mvp: "MVP",
  "most-improved": "MIP",
  pra: "Pts + Rebs + Asts",
  pts: "Points",
  "retro-fmvp": "Estimated pre-1969 Finals MVP",
  rebounds: "REB Champ",
  rebs: "Rebounds",
  rings: "Championships",
  roy: "ROY",
  rpg: "Rebounds per game",
  scoring: "PTS Champ",
  seasons: "YRS",
  spg: "Steals per game",
  steals: "STL Champ",
  stocks: "Stocks - Stls + Blks",
  "three-point-contest": "3-Point Contest Winner",
  "three-point-title": "3PT King",
  "ts-pct": "True shooting",
  "ts-plus": "Era-adjusted TS%",
  "ts-star": "TS+ & TS% combined",
  ts_pct: "True shooting",
  "ws-48": "Win shares per 48",
};

export const RESULT_BADGE_META_BY_ID: Record<string, AchievementBadgeMeta> = {
  "all-defense": { symbol: "DEF", variant: "defense", description: "All-DEF" },
  "all-nba": { symbol: "NBA", variant: "nba", description: "All-NBA" },
  "all-rookie-1st": { symbol: "R1", variant: "rookie", description: "All-Rookie 1st" },
  "all-rookie-2nd": { symbol: "R2", variant: "rookie", description: "All-Rookie 2nd" },
  "all-star": { symbol: "AS", variant: "all-star-logo", description: "AS" },
  "all-star-mvp": { symbol: "\u2605", variant: "all-star-mvp", description: "AS MVP" },
  "aba-all-defense": { symbol: "ADEF", variant: "defense", description: "ABA All-Defense" },
  "aba-all-league": { symbol: "ABA", variant: "nba", description: "All-ABA" },
  "aba-all-star": { symbol: "AAS", variant: "all-star-logo", description: "ABA All-Star" },
  "aba-all-star-mvp": { symbol: "A*", variant: "all-star-mvp", description: "ABA AS MVP" },
  "aba-assists": { symbol: "AAST", variant: "assist", description: "ABA Assist Champ" },
  "aba-champ": { symbol: "ABA", variant: "ring", description: "ABA Champ" },
  "aba-mvp": { symbol: "AM", variant: "mvp", description: "ABA MVP" },
  "aba-playoffs-mvp": { symbol: "AP", variant: "fmvp", description: "ABA Playoff MVP" },
  "aba-rebounds": { symbol: "AREB", variant: "rebound", description: "ABA Rebound Champ" },
  "aba-roy": { symbol: "AROY", variant: "roy", description: "ABA ROY" },
  "aba-scoring": { symbol: "APTS", variant: "points", description: "ABA Scoring Champ" },
  assists: { symbol: "AST", variant: "assist", description: "AST Champ" },
  blocks: { symbol: "BLK", variant: "defense", description: "BLK Champ" },
  dpoy: { symbol: "DPOY", variant: "dpoy", description: "DPOY" },
  fmvp: { symbol: "F", variant: "fmvp", description: "FMVP" },
  mvp: { symbol: "M", variant: "mvp", description: "MVP" },
  "retro-fmvp": { symbol: "F", variant: "retro-fmvp", description: "Estimated pre-1969 Finals MVP" },
  "most-improved": { symbol: "MIP", variant: "rise", description: "MIP" },
  rebounds: { symbol: "REB", variant: "rebound", description: "REB Champ" },
  rings: { symbol: "\u{1F48D}", variant: "ring", description: "Rings" },
  roy: { symbol: "ROY", variant: "roy", description: "ROY" },
  scoring: { symbol: "PTS", variant: "points", description: "PTS Champ" },
  "sixth-man": { symbol: "6th", variant: "sixth", description: "6MOY" },
  steals: { symbol: "STL", variant: "defense", description: "STL Champ" },
  "three-point-contest": {
    symbol: "3PC",
    variant: "three-point-contest",
    description: "3-Point Contest Winner",
    featured: true,
  },
  "three-point-title": {
    symbol: "3PT",
    variant: "three-point-title",
    description: "3PT King",
    featured: true,
  },
};

export const RESULT_BADGE_SCORE_WEIGHT_BY_ID: Record<string, number> = {
  mvp: 8,
  "aba-mvp": 7,
  fmvp: 7.1,
  "aba-playoffs-mvp": 5,
  "retro-fmvp": 4.5,
  "all-nba": 7,
  "aba-all-league": 6,
  scoring: 3,
  "aba-scoring": 2.5,
  assists: 3,
  "aba-assists": 2.5,
  dpoy: 2.5,
  "three-point-title": 2.5,
  rings: 2.4,
  "aba-champ": 2,
  rebounds: 2,
  "aba-rebounds": 1.75,
  "all-defense": 2,
  "aba-all-defense": 1.75,
  steals: 1.5,
  blocks: 1.5,
  "all-star-mvp": 1.1,
  "aba-all-star-mvp": 1,
  roy: 1.1,
  "aba-roy": 1,
  "three-point-contest": 1,
  "all-star": 1,
  "aba-all-star": 0.8,
  "sixth-man": 1,
  "most-improved": 1,
  "all-rookie-1st": 1,
  "all-rookie-2nd": 0.75,
};
